In [28]:
import numpy as np
import pandas as pd

In [2]:
apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])

In [4]:
print("ndim:", apartment.ndim) # число осей (измерений) массива - n.dim: 1
print("shape:", apartment.shape) # размеры массива, для вектора определена только длина - shape: (6, )

ndim: 1
shape: (6,)


In [6]:
# вычислим долю жилой площади в квартире
share_living_space = apartment[1]/apartment[0]
print(share_living_space)

0.5277310924369748


Избавимся от старых признаков, посредством функции delete(), которую предоставляет библиотека numpy. Передадим в значение функции индексы признаков, которые необходимо удалить из нашего массива apartment:

In [7]:
apartment = np.delete(apartment, [0, 1])

И в завершение добавим в конец нашего массива новый признак share_living_space, который сочетает в себе смысл двух старых признаков:

In [8]:
apartment = np.append(apartment, share_living_space)

In [9]:
apartment

array([1.90000000e+01, 2.00000000e+00, 6.05500000e+04, 2.00000000e+00,
       5.27731092e-01])

In [10]:
apartment.shape

(5,)

In [12]:
a = np.array([3,4,5,9])
b = np.array([1, 5, 3, 6])

In [13]:
b*400 - a*200

array([-200, 1200,  200,  600])

In [3]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])

#умножение векторов

np.dot(a, w)

102.0

In [4]:
x = np.array([4, 5, -1])
y = np.array([2, 0, 1])

np.dot(x, y)

7

In [9]:
(4**2 + 6**2 + 1**2)**0.5

7.280109889280518

In [8]:
49**0.5

7.0

In [10]:
import pandas as pd

In [11]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

In [15]:
matrix = Hut_Paradise_DF.values

In [29]:
(matrix[:, 0] / 10)*4

array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

In [22]:
matrix.shape

(9, 6)

In [30]:
time = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])

In [33]:
matrix[:, 4] @ time

1348

In [34]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

In [36]:
np.dot(v*2 + w*-3, u)

0

In [39]:
u_norm=u/np.linalg.norm(u)
v_norm=v/np.linalg.norm(v)
w_norm=w/np.linalg.norm(w)

In [43]:
v_norm

array([ 0.        ,  0.33333333,  0.        ,  0.66666667, -0.66666667])

In [44]:
v

array([ 0,  1,  0,  2, -2])

In [2]:
#-----------------

In [3]:
husband_income = np.array([100,220,140])
wife_income = np.array([150,200,130])
mother_in_law_income = np.array([90,80,100])

husband_consumption = np.array([50,50,60])
wife_consumption = np.array([100,80,140])
mother_in_law_consumption = np.array([100,20,140])

In [6]:
np.matrix([husband_income, wife_income, mother_in_law_income]).T

matrix([[100, 150,  90],
        [220, 200,  80],
        [140, 130, 100]])

In [7]:
np.matrix([husband_consumption, wife_consumption, mother_in_law_consumption]).T

matrix([[ 50, 100, 100],
        [ 50,  80,  20],
        [ 60, 140, 140]])

In [8]:
income = np.matrix([husband_income, wife_income, mother_in_law_income]).T
income*0.87

matrix([[ 87. , 130.5,  78.3],
        [191.4, 174. ,  69.6],
        [121.8, 113.1,  87. ]])

In [10]:
cons = np.matrix([husband_consumption, wife_consumption, mother_in_law_consumption]).T
income*0.87 - cons

matrix([[ 37. ,  30.5, -21.7],
        [141.4,  94. ,  49.6],
        [ 61.8, -26.9, -53. ]])

In [12]:
A = np.array([[1, -1, 2, 4, 0], [8, 2, 0, 5, 3], [0, 1, 2, 1, 2]])
B = np.array([[1, 0, 1, 0], [0, 0, 2, -1], [1, 0, 1, 1], [0, 1, 1, 1], [1, 1, 0, -1]])

In [14]:
np.dot(A, B)

array([[ 3,  4,  5,  7],
       [11,  8, 17,  0],
       [ 4,  3,  5,  0]])

In [15]:
A = np.array([[2, 0], [0, 3]])
B = np.array([[1, 1], [4, 5]])

In [17]:
np.dot(B, A)

array([[ 2,  3],
       [ 8, 15]])

In [18]:
a = np.array([[1, 1], [2, -1], [1, 2]])

In [19]:
np.dot(a, a.T)

array([[2, 1, 3],
       [1, 5, 0],
       [3, 0, 5]])

In [20]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

In [21]:
A@x

array([26, 30])

In [22]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])

In [23]:
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

In [24]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [25]:
A = np.array([x, y, z])

In [26]:
A@A.T

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

In [29]:
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

In [35]:
Count_DF.values

array([[10,  5, 12, 15, 10],
       [ 2, 21,  3, 25,  6],
       [12, 12,  0, 30,  4],
       [ 4,  8, 18, 14,  5],
       [ 6, 25, 27, 25, 18],
       [10,  3,  2, 17, 12],
       [22,  1,  4, 25, 20],
       [ 7,  0, 31, 31, 28]], dtype=int64)

In [32]:
Price_DF.values

array([[2. , 1.5, 1. , 0.8, 1. ],
       [1.8, 2.5, 1. , 1. , 1. ],
       [2. , 2. , 0. , 0.5, 2. ],
       [1.8, 1.2, 2.8, 0.8, 2. ],
       [2.5, 3.5, 2. , 1. , 1.5],
       [5. , 5. , 3. , 2. , 2.5],
       [1.1, 1. , 1.5, 0.5, 1.7],
       [4.5, 4. , 2.5, 1. , 2. ]])

In [33]:
Count_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

In [37]:
Price_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

In [38]:
Count_DF.values[1] * Price_DF.values[1]

array([ 3.6, 52.5,  3. , 25. ,  6. ])

In [44]:
com = np.array([[0.2, 0.2, 0.3, 0.1, 0.1]])

In [52]:
((Count_DF.values*Price_DF.values)@com.T)

array([[11.3 ],
       [15.22],
       [11.9 ],
       [20.6 ],
       [41.9 ],
       [21.2 ],
       [11.49],
       [38.25]])

In [56]:
((Count_DF.values*Price_DF.values)@(1-com).T).T

array([[ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75]])

In [58]:
A = np.array([[2, 0, 0], [0, 1, 0], [0, 0, 4]])

In [59]:
np.linalg.det(A)

7.999999999999998

In [62]:
np.linalg.det(1/A)

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
E:\Anaconda\lib\site-packages\numpy\linalg\linalg.py:2093: RuntimeWarning: invalid value encountered in det
  r = _umath_linalg.det(a, signature=signature)


nan

In [63]:
#------------

In [64]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

In [66]:
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

In [67]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [74]:
np.array([v1, v2, v3, v4])

array([[ 9, 10,  7,  7,  9],
       [ 2,  0,  5,  1,  4],
       [ 4,  0,  0,  4,  1],
       [ 3, -4,  3, -1, -4]])

In [72]:
np.linalg.matrix_rank(np.array([v1, v2, v3, v4]))

4

In [76]:
V = np.array([v1, v2, v3, v4])

In [78]:
V@V.T

array([[360,  96,  73, -35],
       [ 96,  46,  16,   4],
       [ 73,  16,  33,   4],
       [-35,   4,   4,  51]])

In [81]:
np.linalg.det(V@V.T)

3716647.9999999995

In [82]:
np.linalg.inv(V@V.T)

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])