In [2]:
import pandas as pd
import numpy as np

Cпособы создания массива
---

In [3]:
arr1 = np.array([1,2,3,4])

In [6]:
arr1

array([1, 2, 3, 4])

In [5]:
arr1.dtype

dtype('int32')

In [7]:
arr2 = np.array([5,6,7,8], dtype = float)
arr2.dtype

dtype('float64')

In [10]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.shape(arr3)

(3, 3)

In [11]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr3.shape

(3, 3)

In [15]:
df = pd.DataFrame()
x = df.values
type(x)

numpy.ndarray

In [16]:
my_series = pd.Series([5, 6, 7, 8, 9, 10])
my_series.values

array([ 5,  6,  7,  8,  9, 10], dtype=int64)

In [17]:
np.empty(5) # одномерный массив из пяти элементов, память для которого выделена, но не инициализирована

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
np.zeros((10, 7)) # массив размером 10x7, заполненный нулями 

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.ones((3,3,3)) # массив размером 3х3х3, заполненный единицами

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [20]:
np.eye(3) # единичная матрица (элементы главной диагонали равны 1, остальные — 0) размера 3х3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.full((3, 5), 3.14)  # массив 3x5 заполненный числом 3.14

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [22]:
np.arange(0, 21, 7)  # одномерный массив, заполненный числами в диапазоне от 0 до 20 с шагом 7

array([ 0,  7, 14])

In [23]:
np.linspace(0, 1, 5)  # массив из пяти чисел, равномерно распределённых в интервале между 0 и 1 включительно

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
np.random.randint(0, 10, (3, 3))  # массив размера 3х3, заполненный случайными числами из диапазона от 0 до 9 (включительно)

array([[1, 2, 8],
       [9, 0, 0],
       [3, 1, 0]])

In [29]:
my_secret = [x for x in range(1, 301, 7) if x%10 == 7 or x%10 == 1]
np.array([my_secret, [x/2 for x in my_secret], [x-100 for x in my_secret]])

array([[  1. ,  57. ,  71. , 127. , 141. , 197. , 211. , 267. , 281. ],
       [  0.5,  28.5,  35.5,  63.5,  70.5,  98.5, 105.5, 133.5, 140.5],
       [-99. , -43. , -29. ,  27. ,  41. ,  97. , 111. , 167. , 181. ]])

С помощью каких вариантов кода можно создать массив, среднее арифметическое всех элементов главной диагонали которого равно 1?

In [41]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.full((5,5), 1)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [44]:
np.array([[1,2,3,4,5], [5,1,2,3,4], [4,5,1,2,3], [3,4,5,1,2], [2,3,4,5,1]])

array([[1, 2, 3, 4, 5],
       [5, 1, 2, 3, 4],
       [4, 5, 1, 2, 3],
       [3, 4, 5, 1, 2],
       [2, 3, 4, 5, 1]])

In [48]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [49]:
np.array([i for i in range(11) if i%2])

array([1, 3, 5, 7, 9])

In [72]:
first_line = [x*y for x in range(2, 100, 6) for y in range (7, 1, -2)]
second_line = [x ** 0.5 for x in range(1000, 1101, 2)]
third_line = [x**2 for x in range(51)]

big_secret = np.array([first_line, second_line, third_line, second_line, first_line])

Чему равна сумма элементов последнего столбца массива? Ответ округлите до двух цифр после запятой:

In [91]:
result = 0

for i in range(big_secret.shape[0]):
    result += big_secret[i][-1]

In [92]:
result

3154.332495807108

Выделите из каждой строки массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Округлите ответ до двух цифр после запятой:

In [102]:
result_array = []

for i in range(big_secret.shape[0]):
    array = big_secret[0:6, i]
    result_array.append(array)
    

In [105]:
matrix = np.array(result_array)

In [106]:
result = 0

for i in range(matrix.shape[0]):
    result += matrix[i, i]

In [107]:
result

121.37188663699624

Выделите из каждой строки массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [132]:
result_array = []

for i in range(big_secret.shape[0]):
    array = big_secret[i, -5:]
    result_array.append(array)

In [133]:
matrix = np.array(result_array)

In [134]:
matrix

array([[ 460.        ,  276.        ,  686.        ,  490.        ,
         294.        ],
       [  33.04542328,   33.07567082,   33.10589071,   33.13608305,
          33.1662479 ],
       [2116.        , 2209.        , 2304.        , 2401.        ,
        2500.        ],
       [  33.04542328,   33.07567082,   33.10589071,   33.13608305,
          33.1662479 ],
       [ 460.        ,  276.        ,  686.        ,  490.        ,
         294.        ]])

In [137]:
result = 1

for i in range(matrix.shape[0]):
    result *= matrix[i, i]

In [138]:
result

341505315559.2347

Замените на 1 все элементы, у которых оба индекса нечётные, и на -1 все элементы, у которых оба индекса чётные.

In [142]:
for i in range(big_secret.shape[0]):
    for j in range(big_secret.shape[1]):
        if i%2 == 0 and j%2 == 0:
            big_secret[i, j] = -1
        if i%2 != 0 and j%2 != 0:
            big_secret[i, j] = 1
        else:
            continue

Выделите из каждой строки обновлённого массива big_secret первые 5 элементов. Чему равна сумма элементов главной диагонали получившейся матрицы? Введите полученный ответ без изменений и округлений.

In [146]:
result_array = []

for i in range(big_secret.shape[0]):
    array = big_secret[0:6, i]
    result_array.append(array)
    
matrix = np.array(result_array)

result = 0

for i in range(matrix.shape[0]):
    result += matrix[i, i]

In [147]:
result

-1.0

Выделите из каждой строки обновлённого массива big_secret последние 5 элементов. Чему равно произведение элементов главной диагонали получившейся матрицы? Введите полученный результат без изменений и округлений.

In [148]:
result_array = []

for i in range(big_secret.shape[0]):
    array = big_secret[i, -5:]
    result_array.append(array)
    
matrix = np.array(result_array)

result = 1

for i in range(matrix.shape[0]):
    result *= matrix[i, i]

In [149]:
result

-1.0

Операции с массивами

In [150]:
a = np.array([3,6,9])
b = np.array([12,15,18])

result1 = a+b
result2 = b-a
result3 = a*b
result4 = a/b
result5 = a*2
print(a)
print(b)
print('Сумма: {}\nРазность: {}\nПроизведение: {}\nЧастное: {}\nУмножение на число: {}' \
      .format(result1, result2, result3, result4, result5))

[3 6 9]
[12 15 18]
Сумма: [15 21 27]
Разность: [9 9 9]
Произведение: [ 36  90 162]
Частное: [0.25 0.4  0.5 ]
Умножение на число: [ 6 12 18]


In [151]:
my_array = np.array([[1,2,3,4,5], [6,7,8,9,10]])
my_array.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

Для превращения массива одной размерности используется метод reshape.

In [152]:
my_array = np.random.randint(0, 10, 20)

In [153]:
my_array

array([3, 6, 1, 1, 3, 8, 3, 5, 0, 0, 8, 4, 1, 7, 5, 1, 2, 4, 8, 2])

In [154]:
my_array.reshape((4,5))

array([[3, 6, 1, 1, 3],
       [8, 3, 5, 0, 0],
       [8, 4, 1, 7, 5],
       [1, 2, 4, 8, 2]])

Для преобразования многомерного массива в одномерный используется метод flatten:

In [159]:
my_array = np.array([[1,2,3], [11,22,33], [111,222,333]])

In [160]:
my_array

array([[  1,   2,   3],
       [ 11,  22,  33],
       [111, 222, 333]])

In [162]:
my_array.flatten()

array([  1,   2,   3,  11,  22,  33, 111, 222, 333])

Сравнения и маски

In [164]:
my_array = np.random.randint(0, 10, (3,4))

In [165]:
my_array

array([[1, 3, 8, 7],
       [7, 6, 9, 0],
       [0, 2, 8, 3]])

In [166]:
my_array<5

array([[ True,  True, False, False],
       [False, False, False,  True],
       [ True,  True, False,  True]])

In [167]:
my_array[my_array<5]

array([1, 3, 0, 0, 2, 3])

In [168]:
mask = np.array([1, 0, 1, 0], dtype=bool)
my_array[:, mask]

array([[1, 8],
       [7, 9],
       [0, 8]])

Сортировка двумерных массивов

In [171]:
my_array = np.random.randint(0, 10, (4, 6))

In [172]:
my_array

array([[3, 9, 9, 0, 7, 1],
       [5, 4, 6, 6, 7, 3],
       [6, 0, 8, 7, 4, 7],
       [0, 4, 9, 7, 1, 8]])

In [173]:
np.sort(my_array, axis=1)

array([[0, 1, 3, 7, 9, 9],
       [3, 4, 5, 6, 6, 7],
       [0, 4, 6, 7, 7, 8],
       [0, 1, 4, 7, 8, 9]])

In [177]:
np.sort(my_array, axis=0)

array([[0, 0, 6, 0, 1, 1],
       [3, 4, 8, 6, 4, 3],
       [5, 4, 9, 7, 7, 7],
       [6, 9, 9, 7, 7, 8]])

Для выполнения упражнений из следующего блока мы будем использовать массив, созданный с помощью кода:

In [207]:
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]

great_secret = np.array([first, second, third]).T

In [180]:
great_secret.shape

(100, 3)

Чему равна сумма косинусов элементов первой строки массива great_secret? Ответ округлите до двух знаков после запятой.

In [186]:
result = 0
for i in np.cos(great_secret)[0]:
    result += i

In [187]:
result

0.16006721889793019

Чему равна сумма элементов массива great_secret, значение которых больше 50?

In [188]:
result = 0

for i in range(great_secret.shape[0]):
    for j in range(great_secret.shape[1]):
        if great_secret[i, j] > 50: 
            result += great_secret[i, j]

In [189]:
result

5470.0

Переведите массив great_secret в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150? Скопируйте ответ из Jupyter Notebook без изменений.

In [191]:
great_secret.flatten()[150]

7.0710678118654755

Отсортируйте значения столбцов массива great_secret по возрастанию. Чему равна сумма элементов последней строки отсортированного массива? Ответ округлите до двух цифр после запятой.

In [242]:
great_secret.sort(axis=0)

In [243]:
great_secret[-1].sum()

115.12148016521353

In [210]:
great_secret[99]

array([ 5.83827246,  9.94987437, 59.6       ])

In [244]:
great_secret[-1, :].sum()

115.12148016521353

Математические и статистические операции

In [246]:
students = np.array([[1, 135, 34, 4],
                     [2, 160, 43, 5],
                     [3, 163, 40, 4.3],
                     [4, 147, 44, 5],
                     [5, 138, 41, 4.7],
                     [6, 149, 54, 3.9],
                     [7, 136, 39, 4.2],
                     [8, 154, 48, 4.9],
                     [9, 137, 35, 3.7],
                     [10, 165, 60, 4.6]])

In [247]:
students

array([[  1. , 135. ,  34. ,   4. ],
       [  2. , 160. ,  43. ,   5. ],
       [  3. , 163. ,  40. ,   4.3],
       [  4. , 147. ,  44. ,   5. ],
       [  5. , 138. ,  41. ,   4.7],
       [  6. , 149. ,  54. ,   3.9],
       [  7. , 136. ,  39. ,   4.2],
       [  8. , 154. ,  48. ,   4.9],
       [  9. , 137. ,  35. ,   3.7],
       [ 10. , 165. ,  60. ,   4.6]])

In [248]:
mean = np.mean(students[:,-1])
mean

4.430000000000001

In [249]:
median = np.median(students[:,-1])
median

4.449999999999999

In [256]:
corr = np.corrcoef(students[:,2], students[:,-1])
corr

array([[1.        , 0.29801325],
       [0.29801325, 1.        ]])

In [257]:
std = np.std(students[:,-1])
std

0.4517742799230607

In [258]:
np.var(students[:,-2])

60.36

Преобразуйте первые 4 столбца массива my_sin в массив из 10 строк и 2 столбцов. Чему равна сумма элементов первого столбца получившегося массива?

In [259]:
my_array = np.array([[1,2,3,4,5],
                     [6,7,8,9,10],
                     [11,12,13,14,15],
                     [16,17,18,19,20],
                     [21,22,23,24,25]])

In [261]:
my_sin = np.sin(my_array)

In [278]:
sum(my_sin[: , :4].reshape(10,2))

array([2.40571721, 5.23806526])

Создайте массив bigdata, содержащий квадраты всех нечётных чисел в диапазоне от 100 до 1000.  
Чему равно стандартное отклонение для массива bigdata?

In [308]:
bigdata = np.array([ x**2 for x in range(100, 1001) if x%2])

In [321]:
even_index = bigdata[range(0, len(bigdata), 2)]
odd_index = bigdata[range(1, len(bigdata), 2)]

In [322]:
np.corrcoef(even_index, odd_index)

array([[1.        , 0.99999973],
       [0.99999973, 1.        ]])