In [1]:
import numpy as np

In [2]:
v1 = np.array([1, -5])
v2 = np.array([2, 1])
v3 = np.array([1, 1])

In [3]:
A = np.matrix([v1, v2, v3])

In [4]:
A

matrix([[ 1, -5],
        [ 2,  1],
        [ 1,  1]])

In [11]:
b = np.array([1, 2, 2])

In [12]:
w = np.array([1, 1])

In [25]:
aw = A@w

In [28]:
b-aw

matrix([[ 5, -1,  0]])

In [27]:
aw

matrix([[-4,  3,  2]])

----

In [34]:
A = np.matrix([[1, 2], [-3, 1], [1, 2], [1, -1]])

In [35]:
A

matrix([[ 1,  2],
        [-3,  1],
        [ 1,  2],
        [ 1, -1]])

In [36]:
b = np.array([1, 4, 5, 0])

In [38]:
gram = A.T@A

In [46]:
a = np.linalg.inv(gram)

In [47]:
b = A.T@b

In [49]:
a@b.T

matrix([[-0.5],
        [ 1.6]])

In [52]:
np.linalg.matrix_rank(A)

2