In [2]:
import numpy as np # для работы с массивами
import pandas as pd # для работы DataFrame 
import seaborn as sns # библиотека для визуализации статистических данных
import matplotlib.pyplot as plt # для построения графиков

%matplotlib inline

In [3]:
df = pd.read_csv('Admission_Predict_Ver1.1.csv')

In [4]:
df.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [5]:
df.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [6]:
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84  

[500 rows x 9 columns]

In [9]:
C = df.corr()
C

Serial No.  GRE Score  TOEFL Score  University Rating  \
Serial No.           1.000000  -0.103839    -0.141696          -0.067641   
GRE Score           -0.103839   1.000000     0.827200           0.635376   
TOEFL Score         -0.141696   0.827200     1.000000           0.649799   
University Rating   -0.067641   0.635376     0.649799           1.000000   
SOP                 -0.137352   0.613498     0.644410           0.728024   
LOR                 -0.003694   0.524679     0.541563           0.608651   
CGPA                -0.074289   0.825878     0.810574           0.705254   
Research            -0.005332   0.563398     0.467012           0.427047   
Chance of Admit      0.008505   0.810351     0.792228           0.690132   

                        SOP      LOR       CGPA  Research  Chance of Admit   
Serial No.        -0.137352 -0.003694 -0.074289 -0.005332          0.008505  
GRE Score          0.613498  0.524679  0.825878  0.563398          0.810351  
TOEFL Score        0.644410  0.541563  0.810574  0.467012          0.792228  
University Rating  0.728024  0.608651  0.705254  0.427047          0.690132  
SOP                1.000000  0.663707  0.712154  0.408116          0.684137  
LOR                0.663707  1.000000  0.637469  0.372526          0.645365  
CGPA               0.712154  0.637469  1.000000  0.501311          0.882413  
Research           0.408116  0.372526  0.501311  1.000000          0.545871  
Chance of Admit    0.684137  0.645365  0.882413  0.545871          1.000000

In [11]:
df_0 = df[df['Research'] == 0]
C0 = df_0.corr()
C0

Serial No.  GRE Score  TOEFL Score  University Rating  \
Serial No.           1.000000  -0.165248    -0.185665          -0.093655   
GRE Score           -0.165248   1.000000     0.680668           0.384715   
TOEFL Score         -0.185665   0.680668     1.000000           0.495748   
University Rating   -0.093655   0.384715     0.495748           1.000000   
SOP                 -0.199090   0.371424     0.476563           0.607496   
LOR                 -0.018579   0.365864     0.470956           0.484262   
CGPA                -0.138537   0.678476     0.696774           0.516427   
Research                  NaN        NaN          NaN                NaN   
Chance of Admit     -0.002771   0.603827     0.622458           0.428580   

                        SOP      LOR       CGPA  Research  Chance of Admit   
Serial No.        -0.199090 -0.018579 -0.138537       NaN         -0.002771  
GRE Score          0.371424  0.365864  0.678476       NaN          0.603827  
TOEFL Score        0.476563  0.470956  0.696774       NaN          0.622458  
University Rating  0.607496  0.484262  0.516427       NaN          0.428580  
SOP                1.000000  0.618680  0.547098       NaN          0.470188  
LOR                0.618680  1.000000  0.562517       NaN          0.542528  
CGPA               0.547098  0.562517  1.000000       NaN          0.752714  
Research                NaN       NaN       NaN       NaN               NaN  
Chance of Admit    0.470188  0.542528  0.752714       NaN          1.000000

In [13]:
df_1 = df[df['Research'] == 1]
C1 = df_1.corr()
C1

Serial No.  GRE Score  TOEFL Score  University Rating  \
Serial No.           1.000000  -0.094895    -0.140706          -0.058624   
GRE Score           -0.094895   1.000000     0.824170           0.614739   
TOEFL Score         -0.140706   0.824170     1.000000           0.602445   
University Rating   -0.058624   0.614739     0.602445           1.000000   
SOP                 -0.109004   0.613318     0.629436           0.723126   
LOR                  0.010475   0.443374     0.436199           0.573881   
CGPA                -0.049214   0.806720     0.784173           0.692237   
Research                  NaN        NaN          NaN                NaN   
Chance of Admit      0.024458   0.802439     0.787180           0.713094   

                        SOP      LOR       CGPA  Research  Chance of Admit   
Serial No.        -0.109004  0.010475 -0.049214       NaN          0.024458  
GRE Score          0.613318  0.443374  0.806720       NaN          0.802439  
TOEFL Score        0.629436  0.436199  0.784173       NaN          0.787180  
University Rating  0.723126  0.573881  0.692237       NaN          0.713094  
SOP                1.000000  0.591858  0.717750       NaN          0.708238  
LOR                0.591858  1.000000  0.564794       NaN          0.588558  
CGPA               0.717750  0.564794  1.000000       NaN          0.892489  
Research                NaN       NaN       NaN       NaN               NaN  
Chance of Admit    0.708238  0.588558  0.892489       NaN          1.000000

In [16]:
df_0 = df_0.drop('Research', axis=1)

In [18]:
df_0 = df_0.drop('Serial No.', axis=1)

In [40]:
df.columns

Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR ', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')

In [41]:
df_0 = df[df['Research'] == 0]

In [42]:
X = df_0[['TOEFL Score', 'CGPA']]
Y = df_0['Chance of Admit ']

In [45]:
A= np.column_stack((np.ones(220), X))

In [46]:
np.linalg.lstsq(A,Y,rcond=None)

(array([-1.04486443,  0.00442727,  0.14807744]),
 array([1.13772786]),
 3,
 array([1.54898055e+03, 5.02503482e+00, 6.75329627e-01]))

In [50]:
w_hat=np.linalg.inv(A.T@A)@A.T@Y
w_hat

array([-1.04486443,  0.00442727,  0.14807744])

In [51]:
new = np.array([1, 107, 9.1])
new@w_hat

0.7763585301807903

In [77]:
w_hat_l = []

for i in range(w_hat.shape[0]):
    val = w_hat[i]
    w_hat_l.append(round(val, 3))
    
w_hat_new = np.array(w_hat_l)

In [78]:
round(new@w_hat_new, 2)

0.73

In [53]:
# среднее значение вектора
meanTOEFL = df_0['TOEFL Score'].mean()
meanCGPA = df_0['CGPA'].mean()
meanY = Y.mean()

In [54]:
# Центрирование
TOEFL_c = df_0['TOEFL Score'] - meanTOEFL
CGPA_c = df_0['CGPA'] - meanCGPA
Y_c = Y - meanY

In [55]:
# вычисляем длины векторов для нормирования
TOEFL_c_norm = np.linalg.norm(TOEFL_c)
CGPA_c_norm = np.linalg.norm(CGPA_c)
Y_c_norm = np.linalg.norm(Y_c)

In [56]:
TOEFL_st = TOEFL_c / TOEFL_c_norm
CGPA_st = CGPA_c / CGPA_c_norm
Y_st = Y_c / Y_c_norm

In [57]:
A_st=np.column_stack((TOEFL_st, CGPA_st))
A_st

array([[-1.39082915e-02, -3.56567808e-03],
       [-4.19800725e-02, -4.82677452e-02],
       [-2.79441820e-02, -3.38477235e-02],
       [ 5.62711610e-02,  5.26724063e-02],
       [ 1.41634895e-02,  9.41234140e-03],
       [ 4.22352705e-02,  6.70924280e-02],
       [ 8.43429419e-02,  8.15124496e-02],
       [-2.79441820e-02,  3.82523847e-02],
       [ 1.40486504e-01,  2.38323630e-02],
       [ 7.03070514e-02,  8.15124496e-02],
       [-1.54267196e-01, -1.49207897e-01],
       [-7.00518534e-02, -1.34787875e-01],
       [ 2.81993800e-02,  2.38323630e-02],
       [ 1.41634895e-02, -6.26877668e-02],
       [ 1.41634895e-02, -1.05947832e-01],
       [ 5.62711610e-02, -7.71077885e-02],
       [ 1.82594175e-01,  1.24772515e-01],
       [ 2.10665956e-01,  2.11292644e-01],
       [ 8.43429419e-02, -3.38477235e-02],
       [-1.39082915e-02, -7.71077885e-02],
       [-2.79441820e-02, -1.20367853e-01],
       [-7.00518534e-02, -9.15278101e-02],
       [ 1.27599004e-04,  9.41234140e-03],
       [-5.

In [58]:
w_hat_st=np.linalg.inv(A_st.T@A_st)@A_st.T@Y_st.values
w_hat_st

array([0.19044768, 0.62001517])